### ISSUE TITLE
[iOS] React Native 0.77 Support

### ISSUE THREAD

**Issue by delphinebugner** [nandorojo/zeego#141]
## Context
The lib makes iOS app crash at component mount when used with React Native 0.77. 
I did the upgrade to 0.77 following https://expo.dev/changelog/2025-01-21-react-native-0.77 with expo 52.
No pb with React Native 0.76.

## Set-up
Reproduced with:
```yaml
    "expo": "~52.0.27"
    "react-native": "0.77.1",
    "react-native-ios-context-menu": "3.1.0", 
    "react-native-ios-utilities": "5.1.2", # also occurs with 5.0.0-58

   new arch activated
```
## Details
The stack trace looks like this:
```
0   CoreFoundation                	       0x1804b70e0 __exceptionPreprocess + 160
1   libobjc.A.dylib               	       0x18008ede8 objc_exception_throw + 72
2   CoreFoundation                	       0x1804b6c80 -[NSException init] + 0
3   Foundation                    	       0x180eaa40c -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 188
4   Foundation                    	       0x180ea92f0 -[NSObject(NSKeyValueCoding) valueForKey:] + 260
5   App.debug.dylib                 0x107ca2e10 __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2.45 + 316 (RCTComponentData.mm:341)
6   App.debug.dylib           	       0x107ca367c __49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke_2 + 52 (RCTComponentData.mm:367)
7   App.debug.dylib           	       0x107d0a628 RCTPerformBlockWithLogFunction + 408 (RCTLog.mm:167)
```
 
This  objective-C line fails precisely:
![Image](https://github.com/user-attachments/assets/bb75116b-2ce6-4915-8eca-1d1a4bf1888c)

The native error is `valueForUndefinedKey: this class is not key value coding-compliant for the key reactEventHandler."`

Linked to a more generic error message is "Error setting `onMenuWillShow` of RNIContextMenuButton"  - visible here.

<img width="1229" alt="Image" src="https://github.com/user-attachments/assets/e52b75c0-36f7-4a64-9394-5a1ef154a757" />

Note that SafeAreaProvider triggers two "Error setting props" errors but with no crash associated.

I tried other combination of `react-native-ios-utilities` / `react-native-ios-context-menu` version without success. 

cc @dominicstop if you have ideas.

**Comment by nandorojo** [comment]
I've reproduced 0.77 not working in a fresh project. However, I can't even `npx expo run:ios` without it throwing. But your app _does build_ and then crashes at runtime? That is odd indeed...

Reproduction [here](https://github.com/nandorojo/zeego-repro)

```
› Compiling react-native-ios-utilities Pods/react-native-ios-utilities » RNIWrapperViewManager.mm
› Compiling react-native-ios-utilities Pods/react-native-ios-utilities » RNIWrapperView.mm

❌  (node_modules/react-native-ios-utilities/ios/Sources/RNIBaseView/RNIBaseViewShadowNode.h:130:15)

  128 |       yogaStyle.setMinDimension(
  129 |         yoga::Dimension::Width,
> 130 |         yoga::value::points(stateData.minSize.width)
      |               ^ no member named 'value' in namespace 'facebook::yoga'
  131 |       );
  132 |     };
  133 |     


❌  (node_modules/react-native-ios-utilities/ios/Sources/RNIBaseView/RNIBaseViewShadowNode.h:138:15)

  136 |       yogaStyle.setMinDimension(
  137 |         yoga::Dimension::Height,
> 138 |         yoga::value::points(stateData.minSize.height)
      |               ^ no member named 'value' in namespace 'facebook::yoga'
  139 |       );
  140 |     };
  141 |     


❌  (node_modules/react-native-ios-utilities/ios/Sources/RNIBaseView/RNIBaseViewShadowNode.h:146:15)

  144 |       yogaStyle.setMinDimension(
  145 |         yoga::Dimension::Width,
> 146 |         yoga::value::points(stateData.maxSize.width)
      |               ^ no member named 'value' in namespace 'facebook::yoga'
  147 |       );
  148 |     };
  149 |     


❌  (node_modules/react-native-ios-utilities/ios/Sources/RNIBaseView/RNIBaseViewShadowNode.h:154:15)

  152 |       yogaStyle.setMinDimension(
  153 |         yoga::Dimension::Height,
> 154 |         yoga::value::points(stateData.maxSize.height)
      |               ^ no member named 'value' in namespace 'facebook::yoga'
  155 |       );
  156 |     };
  157 |     
```

**Comment by nandorojo** [comment]
Trying these next:

```json
    "@react-native-menu/menu": "1.0.2",
    "expo": "~52.0.37",
    "expo-status-bar": "~2.0.1",
    "react": "18.3.1",
    "react-native": "~0.77.1",
    "react-native-ios-context-menu": "3.1.0",
    "react-native-ios-utilities": "5.1.2",
    "zeego": "^3.0.0-alt.1",
```

**Comment by nandorojo** [comment]
Confirmed: Zeego works with React Native 0.77 with those versions. I'm going to close this issue.

Thank you @dominicstop for your hard work on `react-native-ios-utilities` which made this work.

@delphinebugner please try these and we can re-open if it doesn't work, but it should:

```json
    "react-native-ios-context-menu": "3.1.0",
    "react-native-ios-utilities": "5.1.2",
    "zeego": "^3.0.0-alt.1",
```

**Comment by nandorojo** [comment]
https://github.com/nandorojo/zeego/releases/tag/v3.0.0

I added an upgrade guide here, could you let me know if this works for you?

**Comment by delphinebugner** [comment]
`zeego : ^3.0.0-alt.1` still crashed on my setup, will look more into it later and tell you if I find out why :/

**Comment by nandorojo** [comment]
I assume you set the other exact versions in your deps too?

https://github.com/nandorojo/zeego-repro

This link has it working, it could be a useful isolated repo to test your versions...because it's possible it's actually a different dependency causing issues for you.

FWIW, I had to delete _everything_ (node modules, iOS folder, `.expo` folder), reinstall, and rebuild clean. Close Xcode, etc. Without that, it wouldn't work for me. 

Hope you can get it fixed!

**Comment by delphinebugner** [comment]
I did all that - including the nuke the `node_modules` part - but  `react-native-ios-utilities: 5.0.0-58` is still in my dependancies, and gets called by mistake. This causes the crash.

It's in fact zeego that declares the dependancy - see my `pnpm why react-native-ios-utilities`:

```ts 
dependencies:
react-native-ios-context-menu 3.1.0
└── react-native-ios-utilities 5.1.2 peer
react-native-ios-utilities 5.1.2
zeego 3.0.0
├─┬ react-native-ios-context-menu 3.1.0 peer
│ └── react-native-ios-utilities 5.1.2 peer
└── react-native-ios-utilities 5.0.0-58 // ⚠ here
```
It's indeed in the code: 

https://github.com/nandorojo/zeego/blob/403168d0a45afb89a4ba69a98cfa4d7a20f875f2/packages/zeego/package.json#L138

Maybe my pnpm does not help either 🙃 but you know monorepo stuffs
will nuke again hoping to point to 5.1.2, but it might need to be changed in zeego!

**Comment by nandorojo** [comment]
Did you install using legacy peer deps?

**Comment by nandorojo** [comment]
Wonder if this is a pnpm issue. It worked fine with yarn. But you should be explicitly adding peer deps.

**Comment by delphinebugner** [comment]
Here's the installed dependancies running `pnpm why`: is something wrong with it?

```
dependencies:
@react-native-menu/menu 1.2.2
react-native-ios-context-menu 3.1.0
└── react-native-ios-utilities 5.1.2 peer
react-native-ios-utilities 5.1.2
zeego 3.0.3
├── @react-native-menu/menu 1.2.2 peer
├─┬ react-native-ios-context-menu 3.1.0 peer
│ └── react-native-ios-utilities 5.1.2 peer
└── react-native-ios-utilities 5.1.2 peer
```

The crash stack trace remains the same as in the description

**Comment by nandorojo** [comment]
Depends — are they in your package.json?

> But you should be explicitly adding peer deps.

React Native doesn’t link transitive dependencies unfortunately

**Comment by delphinebugner** [comment]
Yes they are explicitely in the package.json 🙂

**Comment by nandorojo** [comment]
How odd, I wonder if pnpm works in that reproduction repository I made. I’m trying to think of what else it could be…

**Comment by nandorojo** [comment]
Are you using expo prebuild —clean? Do you see the correct versions in your pod folders

**Comment by delphinebugner** [comment]
- Yes I used expo prebuild —clean
- Yes in Podfile.lock I see pods `- react-native-ios-context-menu (3.1.0)`  /  `react-native-ios-utilities (5.1.2)`
- I copied-past your repo example App.tsx in a screen of my app and it crashes too, so it's not linked to a special implementation of DropdownMenu on our side

**Comment by nandorojo** [comment]
Does my repo work on your laptop? Latest Xcode version?

**Comment by delphinebugner** [comment]
Yep just finished to test it on an empty app with RN 0.77, works well 👍 

<img width="501" alt="Image" src="https://github.com/user-attachments/assets/c8f06172-6ddd-4a7c-bc58-c68721c9ce31" />

So definitely something fishy with _my_ setup 😭

**Comment by nandorojo** [comment]
Time to debug

I would incrementally add your dependencies from your package.json to the reproduction 

Then do the same with the config plugins 

And you’ll find the clash

**Comment by liixing** [comment]
I encountered the same issue. In my case, it was with a flashList where a long press triggers a context menu, and a short press triggers a route navigation. I found that if I dismiss the context menu first in the onPress method for the short press, it prevents the crash. Hopefully, this can be helpful to you!

**Comment by ChARCOOL** [comment]
I solved it by updating everything to latest version

package.json
```json
  "dependencies": {
    "@react-native-menu/menu": "1.2.3",
    "@react-native-picker/picker": "2.11.0",
    "@react-navigation/bottom-tabs": "7.3.2",
    "@react-navigation/drawer": "7.3.0",
    "@react-navigation/material-top-tabs": "7.2.2",
    "@react-navigation/native": "7.0.18",
    "@react-navigation/native-stack": "7.3.2",
    "parse-headers": "2.0.6",
    "react": "19.0.0",
    "react-native": "0.78.1",
    "react-native-edge-to-edge": "1.4.3",
    "react-native-gesture-handler": "^2.24.0",
    "react-native-ios-context-menu": "3.1.0",
    "react-native-ios-utilities": "5.1.2",
    "react-native-keychain": "9.2.3",
    "react-native-mmkv": "3.2.0",
    "react-native-nitro-modules": "0.25.2",
    "react-native-pager-view": "6.7.0",
    "react-native-picker-select": "9.3.1",
    "react-native-reanimated": "3.17.1",
    "react-native-safe-area-context": "5.3.0",
    "react-native-screens": "4.9.2",
    "react-native-svg": "15.11.2",
    "react-native-tab-view": "4.0.6",
    "react-native-unistyles": "3.0.0-beta.8",
    "react-native-vector-icons": "10.2.0",
    "react-native-video": "6.11.0",
    "zeego": "3.0.6"
  },
  "devDependencies": {
    "@babel/core": "^7.26.10",
    "@babel/preset-env": "^7.26.9",
    "@babel/runtime": "^7.26.10",
    "@react-native-community/cli": "18.0.0",
    "@react-native-community/cli-platform-android": "18.0.0",
    "@react-native-community/cli-platform-ios": "18.0.0",
    "@react-native-community/cli-types": "18.0.0",
    "@react-native/babel-preset": "0.78.1",
    "@react-native/codegen": "0.78.1",
    "@react-native/eslint-config": "0.78.1",
    "@react-native/gradle-plugin": "0.78.1",
    "@react-native/metro-config": "0.78.1",
    "@react-native/typescript-config": "0.78.1",
    "@types/jest": "^29.5.14",
    "@types/react": "^19.0.12",
    "@types/react-native-vector-icons": "6.4.18",
    "@types/react-test-renderer": "^19.0.0",
    "babel-plugin-module-resolver": "5.0.2",
    "eslint": "^9.23.0",
    "jest": "^29.7.0",
    "prettier": "3.5.3",
    "react-test-renderer": "19.0.0",
    "typescript": "5.8.2"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "pnpm@10.6.5",
  "pnpm": {
    "onlyBuiltDependencies": [
      "react-native-nitro-modules"
    ]
  }
```

**Comment by delphinebugner** [comment]
Hi all 🙂 so you know, the issue was linked to a change introduced in the Codegen config of React Native core, for every users on pnpm + node linker: isolated 

It was fixed by this commit on React Native: https://github.com/facebook/react-native/commit/91d034533e9f52232b351bb88b2ae7b48704e68f

It will be included in React Native 0.80; if you have the issue on an older version, you can patch the commit above
