### ISSUE TITLE
<DropdownMenu.Content> type error 

### ISSUE THREAD

**Issue by Cleover** [nandorojo/zeego#98]
![image](https://github.com/user-attachments/assets/db725e7c-2c14-4cec-b2cf-c7c3e1cf20c6)

Is it possible to fix this type error from showing up on all <DropdownMenu.Content> tags? While the app app still works with the error, its making things a bit painful as most of my files have an error showing.

**Comment by 321paranoiawhy** [comment]
One possible thing can solve this may be change the code like this:

```diff
export type MenuContentProps = {
  children: React.ReactNode
  style?: ViewStyle
--  } & Pick<
++  } & Partial<Pick<
  RadixContentProps,
  | 'loop'
  | 'side'
  | 'align'
  | 'alignOffset'
  | 'avoidCollisions'
  | 'collisionPadding'
  | 'sideOffset'
-- >
++ >>
```

the original code can be found in [this link](https://github.com/nandorojo/zeego/blob/master/packages/zeego/src/menu/types.ts#L62-L74)

**Comment by nandorojo** [comment]
Sorry I missed this earlier.

This actually indicates that for some reason the radix types aren’t being pulled into your app. Are you using yarn or NPM? The partial workaround will work, but only because it’s doing `Partial<any`…I’d ideally like to see why radix types aren’t pulling in if possible.

I’m using yarn and not seeing this issue myself. Which version of zeego are you on? Thanks!

**Comment by nandorojo** [comment]
If you are using NPM, does adding —legacy-peer-deps to your install script help?

**Comment by wcastand** [comment]
i get the error and i use `bun` if that can help :)

**Comment by acdifran** [comment]
seeing the same using pnpm

**Comment by nandorojo** [comment]
you could try installing `@radix-ui/react-dropdown-menu`, though this shouldn't be needed...

**Comment by austin43** [comment]
> you could try installing `@radix-ui/react-dropdown-menu`, though this shouldn't be needed...

I'm using bun, and this does not fix it unfortunately. 

I did notice there were three problematic props that, when removed from the Content type in `lib/typescript/dropdown-menu/dropdown-menu.d.ts`, fix the issue.
* placeholder
* onPointerEnterCapture
* onPointerLeaveCapture

Just found this library so couldn't find where those typescript files come from, but hope this helps.

**Comment by RamiroG8k** [comment]
![image](https://github.com/user-attachments/assets/2925fa23-d1e2-4003-89f1-cfb3311c50c0)


Happens the same with `ContextMenu`, i'm using `npm`

**Comment by xxwangkaimin** [comment]
Although the program can run normally.
As shown in the figure, I used three components: content, label, and item, all of which have type errors.
![image](https://github.com/user-attachments/assets/f1d4f410-7356-45ff-ad69-6bfe3d4f6e51)

**Comment by joshsmith** [comment]
Just want to confirm that for both `DropdownMenu.Content` and `DropdownMenu.CheckboxItem` I am seeing ts errors for missing `placeholder`, `onPointerEnterCapture`,  and `onPointerLeaveCapture`.

**Comment by nandorojo** [comment]
Is this on v2 as well? Can you use —legacy-peer-deps when you run install? I think this is an issue with npm/pnpm potentially

**Comment by bnussman** [comment]
Can confirmed this is introduced by v2. v2 is unuseable until this is fixed

**Comment by joshsmith** [comment]
Yeah, I only started seeing the errors after upping to v2.

**Comment by alarm109** [comment]
Same issue using yarn

**Comment by nandorojo** [comment]
Working on a fix

**Comment by nandorojo** [comment]
Fixed in `2.0.3`, thanks for reporting and for your patience

**Comment by JustJoostNL** [comment]
@nandorojo

In version `2.0.3`, it looks like the TypeScript issue was only fixed for `DropdownMenu.Content`. However, `DropdownMenu.CheckboxItem` still has TS errors, similar to what @joshsmith reported. Specifically, `onPointerEnterCapture`, `onPointerLeaveCapture`, and `placeholder` are still required, which causes errors.

**Comment by JustJoostNL** [comment]
Awesome, thanks!

**Comment by erickreutz** [comment]
I'm using `2.0.4` and this is still a problem for me when using `DropdownMenu.CheckboxItem`

**Comment by nandorojo** [comment]
I’ll check tomorrow, should be a simple fix. New versions of TS have perf improvements but result in issues for putting imported types in generics

**Comment by JustJoostNL** [comment]
`action` is also not recognized as property on `DropdownMenu.Trigger`. I guess that's the same issue?
```
Type '{ children: Element; action: string; }' is not assignable to type 'IntrinsicAttributes & DropdownMenuTriggerProps & RefAttributes<HTMLButtonElement>'.
  Property 'action' does not exist on type 'IntrinsicAttributes & DropdownMenuTriggerProps & RefAttributes<HTMLButtonElement>'
```

**Comment by megacherry** [comment]
I have the same issue, but on DropdownMenu.Label:

```
Type '{}' is missing the following properties from type 'Pick<MenuLabelProps & RefAttributes<HTMLDivElement>, "title" | "color" | "children" | "id" | "style" | "className" | "tabIndex" | ... 248 more ... | "asChild">': onPointerEnterCapture, onPointerLeaveCapture, placeholderts(2739)
```

**Comment by softwarebyze** [comment]
> Just published 2.0.4 which I think would fix this

this issue was fixed for me by upgrading to 2.0.4

**Comment by joaolfr** [comment]
Still facing this issue after upgrading to 2.0.4

> action is also not recognized as property on DropdownMenu.Trigger.

Besides that, action `Press` is not working, only the `LongPress` is recognized.

**Comment by JustJoostNL** [comment]
@nandorojo I have found another type issue:

When using `<DropdownMenu.Label>`, the following properties are required:
`onPointerEnterCapture`
`onPointerLeaveCapture`
`placeholder`

These shouldn't be required on iOS/Android, so they should be optional.

**Comment by nandorojo** [comment]
Yeah this should be an easy fix

**Comment by JustJoostNL** [comment]
Any idea when a new release will land with the type fixes?

**Comment by gunnsteinnskula** [comment]
There seems to be another type issue in `ContextMenu.Root`, the type claims that it does not support `onOpenWillChange` anymore on 2.0.4 while `onOpenChange` works correctly.
It still functions as intended (fires before `onOpenChange`) and is still present in the [docs](https://zeego.dev/components/context-menu#root). 

Current type being
```tsx
interface ContextMenuProps {
    children?: React.ReactNode;
    onOpenChange?(open: boolean): void;
    dir?: Direction;
    modal?: boolean;
}
```

**Comment by nandorojo** [comment]
It looks like `ContextMenu.Root` and `DropdownMenu.Label`, right?

**Comment by nandorojo** [comment]
I think these are all fixed in Zeego v3. Could you let me know?

https://github.com/nandorojo/zeego/releases/tag/v3.0.1

**Comment by nandorojo** [comment]
I'll re-open if any issues remain. Thanks for reporting!

**Comment by JustJoostNL** [comment]
@nandorojo I am on `3.0.5` and I am still experiencing this issue: https://github.com/nandorojo/zeego/issues/98#issuecomment-2599679637

**Comment by nandorojo** [comment]
Fixed in `3.0.6` for `<DropdownMenu.Label>`

**Comment by YZahringer** [comment]
@nandorojo same issue on `SubTrigger`, `Item`, `CheckboxItem` and `ItemIndicator` in `3.0.6`
